#
# Licensed under the GPL License. You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#
# THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR
# PURPOSE.
#

version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.oracle.database.jdbc:ojdbc8
    versions:
    - ">= 21.1.0.0"
  - dependency-name: com.oracle.database.jdbc:ucp
    versions:
    - ">= 21.1.0.0"
  - dependency-name: jakarta.servlet:jakarta.servlet-api
    versions:
    - ">= 5.0.0"
